### ISSUE TITLE
Add API Surfaces

### ISSUE THREAD

**Issue by Turnerj** [Turnerj/devto-dotnet#16]
Currently only the Articles API is really covered by the library (https://docs.dev.to/api/#tag/articles). It would be useful to start adding the other APIs to the library too.

**Comment by fgiuliani** [comment]
@Turnerj I can help with that

**Comment by Turnerj** [comment]
Thanks @fgiuliani ! Is there any particular API you'd like to add first? Happy to take them as individual PRs or one PR with everything, whatever works best for you.

For implementing it, you can use my [`ArticleService` class](https://github.com/Turnerj/devto-dotnet/blob/master/src/DevTo.Api/ArticlesService.cs) as a guide and create an appropriate interface like how I have [`IArticleApi`](https://github.com/Turnerj/devto-dotnet/blob/master/src/DevTo.Api/IArticlesApi.cs). The `ApiService` class provides the helper methods for constructing the requests for GET and PUT.

If you have any questions or need any help, leave a comment and I'll get back to you. 🙂

**Comment by fgiuliani** [comment]
@Turnerj I can start working on comments API. Is that ok?
Thank you!

**Comment by Turnerj** [comment]
Sounds great!

**Comment by fgiuliani** [comment]
Comments API done here
https://github.com/Turnerj/devto-dotnet/pull/24

To continue with the other APIs, should we keep this issue open or should we create separate issues for them?

**Comment by Turnerj** [comment]
Thanks so much for working on this. I've created a few more issues for specific APIs to work on next - just comment on whatever one you want to work on and I'll assign it to you.

If you are really keen, it would be great to be able to standup an instance of DEV on the CI so we can actually test some of the "writing" API endpoints. I've got #20 open if you want to take a shot at it. 🙂
